userspace: scheduling: simple: simple_scheduler.py:
fix bug in 'SimpleScheduler.test_frame_and_record_result': add the missing parameter
'physaddr' in calling 'test_single' function. The bug is as follows:

BUG:
when use the command `./main.py -a frame-by-frame`, the program will crash with the
following error message:

ceback (most recent call last):
  File "./main.py", line 469, in <module>
    scheduler.run(0,num_frames, physmem.SOURCE_FREE_BUDDY_PAGE, options.frames_per_check, max_runtime, options.run_time)
  File "/home/wangxq/repo/rampage-wangxq/userspace/scheduling/simple/simple_scheduler.py", line 79, in run
    self.test_frame_and_record_result(frame_status, allowed_sources)
  File "/home/wangxq/repo/rampage-wangxq/userspace/scheduling/simple/simple_scheduler.py", line 112, in test_frame_and_record_result
    is_ok = (test.test_single(map,0) == Null)
TypeError: test_single() takes exactly 4 arguments (3 given)

Signed-off-by: Wang Xiaoqiang <wang_xiaoq@126.com>